# Generated by Django 3.0.3 on 2020-11-17 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('query', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.RenameModel(
            old_name='category',
            new_name='categories',
        ),
        migrations.CreateModel(
            name='sub_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='subcat_pictures')),
                ('summary', models.TextField(default='summary', max_length=100)),
                ('pcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mainapp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='products_pictures')),
                ('product_no', models.IntegerField(blank=True, default=0)),
                ('summary', models.TextField(default='summary', max_length=100)),
                ('products_description', models.TextField(max_length=3000)),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mainapp.sub_categories')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='product_pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='product_pictures')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='product_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='more_product_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.products')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
