# Generated by Django 3.0.3 on 2020-06-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200627_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.AlterField(
            model_name='categories',
            name='picture',
            field=models.ImageField(blank=True, upload_to='category_pictures'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mainapp.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, upload_to='products_pictures'),
        ),
    ]
