# Generated by Django 3.0.3 on 2020-11-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201118_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_categories',
            old_name='pcategory',
            new_name='category',
        ),
    ]
