# Generated by Django 3.0.3 on 2020-11-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201118_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_categories',
            options={'verbose_name_plural': 'Sub Category'},
        ),
    ]
