# Generated by Django 3.0.3 on 2020-06-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200628_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_no',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
