# Generated by Django 3.1.2 on 2020-10-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_product_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_description',
            field=models.TextField(max_length=3000),
        ),
    ]
